import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { seedSchema, type Seed } from "../src/lib/validation/seed.ts";
import { pathToFileURL } from "node:url";

function sourceId(key: string): string {
  const h = createHash("sha256")
    .update(`findthedead:source:${key}`)
    .digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
}
// SQL literals only; data is never interpolated as executable identifiers.
export function sqlLiteral(value: string | number | boolean | null): string {
  if (value === null) return "null";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error("Nonfinite SQL number");
    return String(value);
  }
  if (typeof value === "boolean") return String(value);
  return "'" + value.replaceAll("'", "''") + "'";
}
export function buildSeed(input: Seed): string {
  const seed = seedSchema.parse(input);
  const lines = [
    "-- Generated by npm run seed:build from data/detroit.seed.json. DEVELOPMENT ONLY.",
    "begin;",
    "set local standard_conforming_strings = on;",
  ];
  const insert = (
    table: string,
    row: Record<string, string | number | boolean | null>,
  ) =>
    lines.push(
      `insert into public.${table} (${Object.keys(row).join(",")}) values (${Object.values(row).map(sqlLiteral).join(",")}) on conflict (id) do nothing;`,
    );
  for (const c of seed.categories) insert("categories", c);
  for (const c of seed.cemeteries) {
    insert("cemeteries", {
      id: c.id,
      slug: c.slug,
      name: c.name,
      city: c.city,
      state: c.state,
      country: c.country,
      status: "draft",
      is_fixture: true,
    });
    // Only update fixture rows; rerunning cannot overwrite a reviewed production record.
    lines.push(
      `update public.cemeteries set location=extensions.st_setsrid(extensions.st_makepoint(${c.longitude},${c.latitude}),4326)::extensions.geography where id=${sqlLiteral(c.id)} and is_fixture;`,
    );
    insert("sources", {
      id: sourceId(c.id),
      source_type: "wikipedia",
      url: c.source_url,
      external_id: null,
      retrieved_at: seed.retrieved_at,
      field: "name,city,state,country,location",
      confidence: 0.75,
      notes: "Cemetery reference point only; not an entrance or grave.",
      cemetery_id: c.id,
    });
  }
  for (const p of seed.people) {
    const {
      categories,
      cemetery_id,
      burial_id,
      location_precision,
      location_confidence,
      source_url,
      ...person
    } = p;
    insert("people", { ...person, status: "draft", is_fixture: true });
    insert("burials", {
      id: burial_id,
      person_id: p.id,
      cemetery_id,
      location_precision,
      location_confidence,
      is_primary: true,
    });
    insert("sources", {
      id: sourceId(p.id),
      source_type: "wikipedia",
      url: source_url,
      external_id: null,
      retrieved_at: seed.retrieved_at,
      field: "name,birth_year,death_year,short_description",
      confidence: 0.75,
      notes:
        "Short original factual label; dates are years only. Publication review pending.",
      person_id: p.id,
    });
    insert("sources", {
      id: sourceId(burial_id),
      source_type: "wikipedia",
      url: source_url,
      external_id: null,
      retrieved_at: seed.retrieved_at,
      field: "cemetery_id",
      confidence: location_confidence,
      notes: "Listed burial; no exact grave coordinate claimed.",
      burial_id,
    });
    lines.push(
      `update public.burials b set source_id=${sqlLiteral(sourceId(burial_id))} where b.id=${sqlLiteral(burial_id)} and exists(select 1 from public.people p where p.id=b.person_id and p.is_fixture);`,
    );
    for (const cat of categories)
      lines.push(
        `insert into public.person_categories(person_id,category_id) values (${sqlLiteral(p.id)},${sqlLiteral(seed.categories.find((c) => c.slug === cat)!.id)}) on conflict do nothing;`,
      );
  }
  lines.push("commit;", "");
  return lines.join("\n");
}
if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const generated = buildSeed(
    seedSchema.parse(
      JSON.parse(
        readFileSync(
          new URL("../data/detroit.seed.json", import.meta.url),
          "utf8",
        ),
      ),
    ),
  );
  const output = new URL("../supabase/seed.sql", import.meta.url);
  if (process.argv.includes("--check")) {
    if (readFileSync(output, "utf8") !== generated)
      throw new Error("Seed SQL is stale; run npm run seed:build");
    console.log("Seed SQL matches validated input.");
  } else {
    writeFileSync(output, generated);
    console.log("Generated development SQL seed.");
  }
}
